### Delete a person by ID
DELETE http://localhost:3001/api/persons/1407
Content-Type: application/json

### Verify the deletion by trying to get the deleted person
GET http://localhost:3001/api/persons
